### ISSUE TITLE
Submodules require SSH

### ISSUE THREAD

**Issue by DanSGiesbrecht** [DanSGiesbrecht/humidity-hardware#3]
Updating submodules will fail if SSH is not configured. Suggest changing it to HTTPS.

**Comment by Logan-Hunter** [comment]
... Are you asking me to change how git works? I'm confused

**Comment by DanSGiesbrecht** [comment]
Is it not a matter of changing the `.gitmodules` URL's from `SSH` to `HTTPS`?

**Comment by Logan-Hunter** [comment]
Yeah but you super don't want to do that, because then you'd have to log in to github for every single submodule you try to update, unless the submodule happens to be public

**Comment by DanSGiesbrecht** [comment]
All submodules being used are public for this project, though.
